image: node:10.9.0

pages:
  stage: deploy
  script:
  - yarn install
  - yarn build
  - rm -rf public
  - mv build public
  artifacts:
    paths:
    - public
  cache:
    paths:
      - node_modules
  only:
  - master
