language: node_js
node_js:
  - 10.14
before_deploy:
  - yarn build
after_deploy:
  - yarn coverage
deploy:
  provider: pages
  local-dir: build
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
